// Weakest-link confidence for a single assertion, and the grade the GUI paints.
//
// Two confidences travel with every cited claim and the API is emphatic that
// they are not interchangeable: `assertion_confidence` rates the conclusion,
// `source_confidence` rates the document it was drawn from. A careful reading
// of a weak source is not a strong claim.
//
// So the grade is the weaker of the two rather than either alone. That is the
// same weakest-link rule `/exposure` already applies along a two-edge path, and
// for the same reason given there: the two ratings are not independent, and the
// graph carries nothing that would let them be combined into a joint
// probability. Taking the minimum is not collapsing them — both are still
// reported separately, and the popover names which one set the grade.
//
// Over the current seed data this moves 18 of 692 assertions. The point is not
// the count; it is that those 18 are precisely the rows that would otherwise
// paint a confident reading of a weak document green.

import type { ApiProvenance, ApiSourceRef } from "./api";

/** Four states, because "unrated" is a real answer and is not "high". */
export type ConfidenceGrade = "HIGH" | "MEDIUM" | "LOW" | "UNRATED";

const RANK: Record<ConfidenceGrade, number> = {
  HIGH: 3,
  MEDIUM: 2,
  LOW: 1,
  UNRATED: 0,
};

const BY_RANK: readonly ConfidenceGrade[] = ["UNRATED", "LOW", "MEDIUM", "HIGH"];

/** Anything the API did not rate, or rated with a value we do not know, is
 *  UNRATED. Guessing HIGH for an unrecognised string would invent a rating. */
export function toGrade(value: string | null | undefined): ConfidenceGrade {
  return value != null && value in RANK ? (value as ConfidenceGrade) : "UNRATED";
}

export interface DisplayedConfidence {
  /** What the dot paints: the weaker of the two inputs below. */
  readonly grade: ConfidenceGrade;
  readonly assertion: ConfidenceGrade;
  /** Null where the assertion rests on no document at all, which is different
   *  from resting on one nobody has rated. */
  readonly source: ConfidenceGrade | null;
  /** Which input the grade came from, so the popover can say why it is what it
   *  is. BOTH where the two agree and neither alone is the constraint. */
  readonly binding: "ASSERTION" | "SOURCE" | "BOTH";
}

/**
 * The grade for one assertion, given the document it cites (where it cites one).
 *
 * An unrated *document* drags the grade to UNRATED rather than being skipped.
 * An unassessed source is not a weak one, but it is also not a warrant, and the
 * grey dot reads as "go rate this document" rather than as a verdict on it.
 * No row in the current data hits this: all 89 sources carry a rating.
 */
export function displayedConfidence(
  provenance: ApiProvenance,
  source: ApiSourceRef | null | undefined,
): DisplayedConfidence {
  const assertion = toGrade(provenance.assertion_confidence);
  // A provenance naming no source_id rests on no document by design — a
  // judgment, an inference, a model estimate. Only the assertion can grade it.
  if (!provenance.source_id || !source) {
    return { grade: assertion, assertion, source: null, binding: "ASSERTION" };
  }
  const sourceGrade = toGrade(source.source_confidence);
  const weakest = Math.min(RANK[assertion], RANK[sourceGrade]);
  return {
    grade: BY_RANK[weakest],
    assertion,
    source: sourceGrade,
    binding:
      RANK[assertion] === RANK[sourceGrade]
        ? "BOTH"
        : RANK[sourceGrade] < RANK[assertion]
          ? "SOURCE"
          : "ASSERTION",
  };
}

export const GRADE_LABEL: Record<ConfidenceGrade, string> = {
  HIGH: "High",
  MEDIUM: "Medium",
  LOW: "Low",
  UNRATED: "Unrated",
};

/** Fraction of the circle the dot fills. The grade is carried twice — hue and
 *  area — because green/amber/red at 10px is the textbook deuteranopia failure
 *  and colour alone cannot be the only carrier of meaning. */
export const GRADE_FILL: Record<ConfidenceGrade, number> = {
  HIGH: 1,
  MEDIUM: 0.5,
  LOW: 0.25,
  UNRATED: 0,
};

export const GRADE_VAR: Record<ConfidenceGrade, string> = {
  HIGH: "--color-confidence-high",
  MEDIUM: "--color-confidence-med",
  LOW: "--color-confidence-low",
  UNRATED: "--color-confidence-none",
};

/** What a provenance type means for a claim resting on no document. Keyed by
 *  `ProvenanceType` in api/src/models/provenance.py. */
export const UNSOURCED_NOTE: Record<string, string> = {
  JUDGMENT: "An analyst judgment. It rests on no document.",
  INFERRED: "Inferred from other edges in the graph. It rests on no document.",
  MODEL_ESTIMATE: "A model estimate. It rests on no document.",
  AUTOMATED:
    "Generated by the inferred-relationship layer, which states that it is not evidence.",
  UNKNOWN: "The graph does not record how this was arrived at.",
};

/** Renders the API's SCREAMING_SNAKE enums as prose. */
export function humanise(value: string): string {
  const s = value.replace(/_/g, " ").toLowerCase();
  return s.charAt(0).toUpperCase() + s.slice(1);
}
